### ISSUE TITLE
CSS isn't working

### ISSUE THREAD

**Issue by evaboogaard** [evaboogaard/blok-tech-team#15]
sos i might be linking this wrong but how do i fix this?

<img width="664" alt="Schermafbeelding 2022-03-28 om 11 51 20" src="https://user-images.githubusercontent.com/94062754/160373163-3ca798c0-3a3b-41c0-bbbd-bb6e90494215.png">
<img width="458" alt="Schermafbeelding 2022-03-28 om 11 51 25" src="https://user-images.githubusercontent.com/94062754/160373175-182f882c-78f2-4d7d-8f4f-550c8c4437fc.png">

**Comment by maxvl3** [comment]
try changing the href to: "../../static/style/main.css"

**Comment by evaboogaard** [comment]
It works! thanks so much
