### ISSUE TITLE
Likes page doesn't show restaurants

### ISSUE THREAD

**Issue by PipHarsveld** [evaboogaard/blok-tech-team#33]
Hi,
For some reason the likes page doesn't show the list with liked restaurants.

Does anyone have any idea how i can fix this?

![image](https://user-images.githubusercontent.com/54938035/160619463-4f3b1041-3f50-4412-989e-4f79ee6a0d21.png)
![image](https://user-images.githubusercontent.com/54938035/160619550-2bc0a616-014e-4af7-ba5c-57d9163512c0.png)

**Comment by maxvl3** [comment]
Try removing the route to /likes in routers.js. Probably something is going wrong because there is now .get('/likes) in 2 files.

![Schermafbeelding 2022-03-29 om 16 32 33](https://user-images.githubusercontent.com/94384526/160635818-9bdacc67-de09-40b9-8062-09ffee4ea450.png)

this worked for me

**Comment by PipHarsveld** [comment]
Yess that works, thanks!!
