### ISSUE TITLE
Deleting user id doesn't work 

### ISSUE THREAD

**Issue by evaboogaard** [evaboogaard/blok-tech-team#57]
If I try to delete my user it deletes the first one in our database list, instead of the user that's logged in.

```javascript 
router.post("/delete", (req, res) => {
  User.findOneAndDelete({ id: req.body._id })
    .then(console.log("deleted account, yay!"), res.redirect("/"))
    .catch((error) => {
      res.status(400).json({
        error: error,
      });
    });
});
```

Not sure what to do about it, this worked fine with my own app for A1 so if someone could figure it out that'd be cool

**Comment by PipHarsveld** [comment]
Our database is called "users", so maybe change "User.findOneAndDelete" to "users.findOneAndDelete"? Not sure but maybe it'll work

**Comment by evaboogaard** [comment]
users is undefined, doesn't work unfortunately :(

**Comment by PipHarsveld** [comment]
Hmm, then I think the problem is in "id: req.body._id", if it's undefined it will remove the first one from the database list

**Comment by evaboogaard** [comment]
Fixed it, had to mess around with sessions
