### ISSUE TITLE
What bundler do we like to use? 

### ISSUE THREAD

**Issue by annekesteller** [evaboogaard/blok-tech-team#62]
Review ' Bundlers ' in the wiki to read about all the different bundlers that we can choose from.

**Comment by PipHarsveld** [comment]
I've read in your topic that Webpack the easiest is to use, so I think we shouldn't make it to hard for ourselfs and choose Webpack. I don't know what the others think?

**Comment by annekesteller** [comment]
After careful consideration, research, and a lot of errors and headaches lol  I would like to switch to Gulp if everyone is okay with that!

**Comment by evaboogaard** [comment]
Gulp sounds good to me

**Comment by PipHarsveld** [comment]
Sure!
